
Maci\PageBundle\Entity\Blog\Related:
    type:  entity
    table: maci_blog_related_posts
    repositoryClass: Maci\PageBundle\Repository\Blog\RelatedRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 15
        position:
            type: integer
            nullable: true
    manyToOne:
        sourcePost:
            targetEntity: Maci\PageBundle\Entity\Blog\Post
            inversedBy: targets
        targetPost:
            targetEntity: Maci\PageBundle\Entity\Blog\Post
            inversedBy: sources
