
Maci\PageBundle\Entity\Blog\Item:
    type:  entity
    table: maci_blog_media_item
    repositoryClass: Maci\PageBundle\Repository\Blog\ItemRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        favourite:
            type: boolean
        position:
            type: integer
            nullable: true
    manyToOne:
        post:
            targetEntity: Maci\PageBundle\Entity\Blog\Post
            inversedBy: items
        media:
            targetEntity: Maci\PageBundle\Entity\Media\Media
