
Maci\PageBundle\Entity\Blog\Post:
    type:  entity
    table: maci_blog_post
    repositoryClass: Maci\PageBundle\Repository\Blog\PostRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        subtitle:
            type: string
            length: 255
            nullable: true
        preheader:
            type: text
            nullable: true
        header:
            type: text
            nullable: true
        markdown:
            type: text
            nullable: true
        content:
            type: text
            nullable: true
        status:
            type: string
            length: 15
            nullable: true
        path:
            type: string
            length: 63
            nullable: true
        link:
            type: string
            length: 31
            nullable: true
        permalink:
            type: string
            length: 127
            nullable: true
        meta_title:
            type: string
            length: 63
            nullable: true
        meta_description:
            type: string
            length: 191
            nullable: true
        locale:
            type: string
            length: 10
        created:
            type: datetime
        updated:
            type: datetime
        pubblished:
            type: datetime
            nullable: true
        removed:
            type: boolean
    manyToOne:
        author:
            targetEntity: Maci\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
        preview:
            targetEntity: Maci\PageBundle\Entity\Media\Media
    oneToMany:
        items:
            targetEntity: Maci\PageBundle\Entity\Blog\Item
            mappedBy: post
            orderBy: { 'position': ASC }
        sources:
            targetEntity: Maci\PageBundle\Entity\Blog\Related
            mappedBy: sourcePost
            orderBy: { 'position': ASC }
        targets:
            targetEntity: Maci\PageBundle\Entity\Blog\Related
            mappedBy: targetPost
            orderBy: { 'position': ASC }
    manyToMany:
        tags:
            targetEntity: Maci\PageBundle\Entity\Blog\Tag
            inversedBy: posts
            joinTable:
                name: maci_blog_posts_and_tags
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setUpdatedValue, setCreatedValue ]
        preUpdate: [ setUpdatedValue ]
