
Maci\PageBundle\Entity\Mailer\SlideMedia:
    type:  entity
    table: maci_mailer_slide_media
    # repositoryClass: Maci\PageBundle\Repository\Mailer\SlideMediaRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        position:
            type: smallint
    manyToOne:
        media:
            targetEntity: Maci\PageBundle\Entity\Media\Media
            inversedBy: mailSlideItems
        slide:
            targetEntity: Maci\PageBundle\Entity\Mailer\Slide
            inversedBy: mediaItems
