
Maci\PageBundle\Entity\Mailer\Subscriber:
    type:  entity
    table: maci_mailer_subscriber
    repositoryClass: Maci\PageBundle\Repository\Mailer\SubscriberRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 63
            nullable: true
        mail:
            type: string
            length: 63
        locale:
            type: string
            length: 2
        token:
            type: string
            length: 32
        removed:
            type: boolean
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        user:
            targetEntity: Maci\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setNameValue, setCreatedValue, setUpdatedValue ]
        preUpdate: [ setUpdatedValue ]
