
Maci\PageBundle\Entity\Mailer\Slide:
    type:  entity
    table: maci_mailer_slide
    # repositoryClass: Maci\PageBundle\Repository\Mailer\SlideRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 63
            nullable: true
        content:
            type: text
            nullable: true
        type:
            type: string
            length: 15
            nullable: true
        link:
            type: string
            length: 255
            nullable: true
        video:
            type: string
            length: 255
            nullable: true
        position:
            type: smallint
    manyToOne:
        media:
            targetEntity: Maci\PageBundle\Entity\Media\Media
        mail:
            targetEntity: Maci\PageBundle\Entity\Mailer\Mail
            inversedBy: slides
        parent:
            targetEntity: Maci\PageBundle\Entity\Mailer\Slide
            inversedBy: children
    oneToMany:
        children:
            targetEntity: Maci\PageBundle\Entity\Mailer\Slide
            mappedBy: parent
        mediaItems:
            targetEntity: Maci\PageBundle\Entity\Mailer\SlideMedia
            mappedBy: slide
            cascade: ["persist","remove"]
        productItems:
            targetEntity: Maci\PageBundle\Entity\Mailer\SlideProduct
            mappedBy: slide
            cascade: ["persist","remove"]
