
Maci\PageBundle\Entity\Media\Media:
    type: entity
    table: maci_media
    repositoryClass: Maci\PageBundle\Repository\Media\MediaRepository
    fields:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 127
            nullable: true
        description:
            type: text
            nullable: true
        original:
            type: string
            length: 127
            nullable: true
        path:
            type: string
            length: 255
            nullable: true
        public:
            type: boolean
        type:
            type: string
            length: 15
            nullable: true
        mimetype:
            type: string
            length: 31
            nullable: true
        token:
            type: string
            length: 127
            nullable: true
        created:
            type: datetime
        updated:
            type: datetime
    manyToMany:
        tags:
            targetEntity: Maci\PageBundle\Entity\Media\Tag
            inversedBy: media
            joinTable:
                name: maci_media_media_and_tags
                joinColumns:
                    media_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    manyToOne:
        user:
            targetEntity: Maci\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        permissions:
            targetEntity: Permission
            mappedBy: media
    lifecycleCallbacks:
        prePersist: [ setUpdatedValue, setCreatedValue, fileUpload ]
        preUpdate: [ setUpdatedValue, fileUpload ]
        postRemove: [ removeUpload ]
