
Maci\PageBundle\Entity\PageTranslation:
    type: entity
    table: maci_page_translation
    fields:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 127
        subtitle:
            type: string
            length: 127
            nullable: true
        description:
            type: text
            nullable: true
        header:
            type: text
            nullable: true
        content:
            type: text
            nullable: true
        meta_title:
            type: string
            length: 63
            nullable: true
        meta_description:
            type: string
            length: 191
            nullable: true
        locale:
            type: string
            length: 10
