
Maci\PageBundle\Entity\Page\Page:
    type:  entity
    table: maci_page
    repositoryClass: Maci\PageBundle\Repository\Page\PageRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 127
        subtitle:
            type: string
            length: 127
            nullable: true
        description:
            type: text
            nullable: true
        header:
            type: text
            nullable: true
        content:
            type: text
            nullable: true
        text:
            type: text
            nullable: true
        footer:
            type: text
            nullable: true
        menu_title:
            type: string
            length: 127
            nullable: true
        meta_title:
            type: string
            length: 63
            nullable: true
        meta_description:
            type: string
            length: 191
            nullable: true
        status:
            type: string
            length: 15
            nullable: true
        map:
            type: text
            nullable: true
        path:
            type: string
            length: 63
            nullable: true
        redirect:
            type: string
            length: 63
            nullable: true
        template:
            type: string
            length: 63
            nullable: true
        locale:
            type: string
            length: 10
        created:
            type: datetime
        updated:
            type: datetime
        removed:
            type: boolean
    manyToOne:
        parent:
            targetEntity: Maci\PageBundle\Entity\Page\Page
            inversedBy: children
    oneToMany:
        children:
            targetEntity: Maci\PageBundle\Entity\Page\Page
            mappedBy: parent
        slides:
            targetEntity: Maci\PageBundle\Entity\Page\Slide
            mappedBy: page
    lifecycleCallbacks:
        prePersist: [ setUpdatedValue, setCreatedValue ]
        preUpdate: [ setUpdatedValue ]
