
Maci\PageBundle\Entity\Page:
    type:  entity
    table: maci_page
    repositoryClass: Maci\PageBundle\Repository\PageRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 127
        subtitle:
            type: string
            length: 127
            nullable: true
        description:
            type: text
            nullable: true
        header:
            type: text
            nullable: true
        content:
            type: text
            nullable: true
        text:
            type: text
            nullable: true
        footer:
            type: text
            nullable: true
        meta_title:
            type: string
            length: 63
            nullable: true
        meta_description:
            type: string
            length: 191
            nullable: true
        status:
            type: string
            length: 15
            nullable: true
        map:
            type: text
            nullable: true
        path:
            type: string
            length: 63
            nullable: true
        template:
            type: string
            length: 63
            nullable: true
        locale:
            type: string
            length: 10
        created:
            type: datetime
        updated:
            type: datetime
        removed:
            type: boolean
    manyToOne:
        album:
            targetEntity: Maci\MediaBundle\Entity\Album
        gallery:
            targetEntity: Maci\MediaBundle\Entity\Album
        slider:
            targetEntity: Maci\MediaBundle\Entity\Album
        slides:
            targetEntity: Maci\MediaBundle\Entity\Album
        category:
            targetEntity: Maci\ProductBundle\Entity\Category
        tag:
            targetEntity: Maci\BlogBundle\Entity\Tag
        parent:
            targetEntity: Page
            inversedBy: children
    oneToMany:
        children:
            targetEntity: Page
            mappedBy: parent
    lifecycleCallbacks:
        prePersist: [ setUpdatedValue, setCreatedValue ]
        preUpdate: [ setUpdatedValue ]


