
Maci\PageBundle\Entity\Page\Slide:
    type:  entity
    table: maci_page_slide
    # repositoryClass: Maci\PageBundle\Repository\Page\SlideRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 63
            nullable: true
        content:
            type: text
            nullable: true
        type:
            type: string
            length: 15
            nullable: true
        link:
            type: string
            length: 255
            nullable: true
        video:
            type: string
            length: 255
            nullable: true
        position:
            type: smallint
    manyToOne:
        album:
            targetEntity: Maci\PageBundle\Entity\Media\Album
        media:
            targetEntity: Maci\PageBundle\Entity\Media\Media
        page:
            targetEntity: Maci\PageBundle\Entity\Page\Page
            inversedBy: slides
        parent:
            targetEntity: Maci\PageBundle\Entity\Page\Slide
            inversedBy: children
    oneToMany:
        children:
            targetEntity: Maci\PageBundle\Entity\Page\Slide
            mappedBy: parent
            orderBy: { 'position': ASC }
