
Maci\PageBundle\Entity\Shop\Record:
    type:  entity
    table: maci_record
    # repositoryClass: Maci\PageBundle\Repository\Shop\RecordRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 7
        code:
            type: string
            length: 13
        barcode:
            type: string
            length: 13
            nullable: true
        brand:
            type: string
            length: 31
            nullable: true
        category:
            type: string
            length: 63
        price:
            type: decimal
            precision: 5
            scale: 2
        quantity:
            type: integer
        data:
            type: json
            nullable: true
        recorded:
            type: datetime
    manyToOne:
        parent:
            targetEntity: Maci\PageBundle\Entity\Shop\RecordSet
            inversedBy: children
    lifecycleCallbacks:
        prePersist: [ setRecordedValue ]

