
Maci\PageBundle\Entity\Shop\Product:
    type:  entity
    table: maci_product
    repositoryClass: Maci\PageBundle\Repository\Shop\ProductRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 15
        name:
            type: string
            length: 127
        path:
            type: string
            length: 63
        type:
            type: string
            length: 7
            nullable: true
        status:
            type: string
            length: 7
            nullable: true
        description:
            type: text
            nullable: true
        composition:
            type: text
            nullable: true
        brand:
            type: string
            length: 31
            nullable: true
        variant:
            type: string
            length: 31
            nullable: true
        meta_title:
            type: string
            length: 95
            nullable: true
        meta_description:
            type: string
            length: 191
            nullable: true
        price:
            type: decimal
            precision: 5
            scale: 2
            nullable: true
        sale:
            type: decimal
            precision: 5
            scale: 2
            nullable: true
        buyed:
            type: integer
        quantity:
            type: integer
        selled:
            type: integer
        position:
            type: integer
            nullable: true
        data:
            type: json
            nullable: true
        locale:
            type: string
            length: 10
        limited:
            type: boolean
        shipment:
            type: boolean
        public:
            type: boolean
        removed:
            type: boolean
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        parent:
            targetEntity: Maci\PageBundle\Entity\Shop\Product
            inversedBy: children
        preview:
            targetEntity: Maci\PageBundle\Entity\Media\Media
            cascade: ["persist", "remove"]
        cover:
            targetEntity: Maci\PageBundle\Entity\Media\Media
            cascade: ["persist", "remove"]
    oneToMany:
        children:
            targetEntity: Maci\PageBundle\Entity\Shop\Product
            mappedBy: parent
            orderBy: { 'position': ASC }
        categoryItems:
            targetEntity: Maci\PageBundle\Entity\Shop\CategoryItem
            mappedBy: product
            orderBy: { 'position': ASC }
            cascade: ["persist", "remove"]
        mediaItems:
            targetEntity: Maci\PageBundle\Entity\Shop\MediaItem
            mappedBy: product
            orderBy: { 'position': ASC }
            cascade: ["persist", "remove"]
    lifecycleCallbacks:
        prePersist: [ setUpdatedValue, setCreatedValue, setPathValue ]
        preUpdate: [ setUpdatedValue ]
