
Maci\PageBundle\Entity\Shop\RecordSet:
    type:  entity
    table: maci_record_set
    # repositoryClass: Maci\PageBundle\Repository\Shop\RecordRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 127
        recorded:
            type: datetime
    manyToOne:
        category:
            targetEntity: Maci\PageBundle\Entity\Shop\SetCategory
            inversedBy: recordSets
        supplier:
            targetEntity: Maci\PageBundle\Entity\Shop\Supplier
            inversedBy: recordSets
    oneToMany:
        children:
            targetEntity: Maci\PageBundle\Entity\Shop\Record
            mappedBy: parent
            orderBy: { 'id': ASC }
    lifecycleCallbacks:
        prePersist: [ setRecordedValue ]
