
maci_page_contacts:
    pattern:  /{_locale}/contacts
    defaults: { _controller: MaciPageBundle:Default:contacts }

maci_page_privacy:
    pattern:  /{_locale}/privacy
    defaults: { _controller: MaciPageBundle:Default:privacy }

# ---> SHow Page
maci_page:
    pattern:  /{_locale}/{path}
    defaults: { _controller: MaciPageBundle:Default:page }

# ---> Local Homepage
maci_homepage:
    pattern:  /{_locale}
    defaults: { _controller: MaciPageBundle:Default:localIndex }

# ---> Locale Redirect
homepage:
    pattern:  /
    defaults: { _controller: MaciPageBundle:Default:index }


