
maci_start_popup:
    pattern:  /session/start-popup
    defaults: { _controller: MaciPageBundle:Default:startPopup }

maci_page_contacts:
    pattern:  /{_locale}/contacts
    defaults: { _controller: MaciPageBundle:Default:contacts }

maci_page_privacy:
    pattern:  /{_locale}/privacy
    defaults: { _controller: MaciPageBundle:Default:privacy }

# ---> Page Not Found
maci_page_not_found:
    pattern:  /{_locale}/page-not-found
    defaults: { _controller: MaciPageBundle:Default:pageNotFound }

# ---> Show Page
maci_page:
    pattern:  /{_locale}/{path}
    defaults: { _controller: MaciPageBundle:Default:page }

# ---> Local Homepage
maci_homepage:
    pattern:  /{_locale}
    defaults: { _controller: MaciPageBundle:Default:localIndex }

# ---> Locale Redirect
homepage:
    pattern:  /
    defaults: { _controller: MaciPageBundle:Default:index }


