
maci_start_popup:
    pattern:  /session/start-popup
    defaults: { _controller: MaciPageBundle:Default:startPopup }

# ---> Page Not Found
maci_page_not_found:
    pattern:  /{_locale}/page-not-found
    defaults: { _controller: MaciPageBundle:Default:pageNotFound }
    requirements:
        _locale: %r_locales%

# ---> Show Page
maci_page:
    pattern:  /{_locale}/{path}
    defaults: { _controller: MaciPageBundle:Default:page }
    requirements:
        _locale: %r_locales%

# ---> Local Homepage
maci_homepage:
    pattern:  /{_locale}
    defaults: { _controller: MaciPageBundle:Default:localIndex }
    requirements:
        _locale: %r_locales%

# ---> Locale Redirect
homepage:
    pattern:  /
    defaults: { _controller: MaciPageBundle:Default:index }


