
services:

    maci_page.form.type.page:
        class: Maci\PageBundle\Form\Type\PageType
        tags:
            - { name: form.type, alias: page }

    maci_page.menu_builder:
        class: Maci\PageBundle\Menu\PageMenuBuilder
        arguments: ["@knp_menu.factory","@security.context","@doctrine.orm.entity_manager","@maci.translator"]

    maci_page.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: maci_page.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    maci_page.menu.left:
        class: Knp\Menu\MenuItem
        factory_service: maci_page.menu_builder
        factory_method: createLeftMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: left }

    maci_page.menu.terms:
        class: Knp\Menu\MenuItem
        factory_service: maci_page.menu_builder
        factory_method: createTermsMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: terms }

    maci_page.menu.contacts:
        class: Knp\Menu\MenuItem
        factory_service: maci_page.menu_builder
        factory_method: createContactsMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: shop_contacts }

    maci_page.shop_menu_builder:
        class: Maci\PageBundle\Menu\ShopMenuBuilder
        arguments: ["@knp_menu.factory","@security.context","@doctrine.orm.entity_manager","@maci.translator"]

    maci_page.menu.shop_customer_service:
        class: Knp\Menu\MenuItem
        factory_service: maci_page.shop_menu_builder
        factory_method: createCustomerServiceMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: shop_customer_service }

    maci_page.menu.shop_terms:
        class: Knp\Menu\MenuItem
        factory_service: maci_page.shop_menu_builder
        factory_method: createTermsMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: shop_terms }
