
services:

    maci_page.form.type.page:
        class: Maci\PageBundle\Form\Type\PageType
        tags:
            - { name: form.type, alias: page }

    maci_page.menu_builder:
        class: Maci\PageBundle\Menu\PageMenuBuilder
        arguments: ["@knp_menu.factory","@doctrine.orm.entity_manager","@maci.translator"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createLeftMenu, alias: left }
            - { name: knp_menu.menu_builder, method: createTermsMenu, alias: terms }
            - { name: knp_menu.menu_builder, method: createContactsMenu, alias: shop_contacts }

    maci_page.shop_menu_builder:
        class: Maci\PageBundle\Menu\ShopMenuBuilder
        arguments: ["@knp_menu.factory","@maci.translator"]
        tags:
            - { name: knp_menu.menu_builder, method: createCustomerServiceMenu, alias: shop_customer_service }
            - { name: knp_menu.menu_builder, method: createTermsMenu, alias: shop_terms }
