<?php

namespace Maci\PageBundle\Repository\Blog;

/**
 * RelatedPostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedPostsRepository extends \Doctrine\ORM\EntityRepository
{
}
