<?php

namespace Maci\PageBundle\Repository\Blog;

/**
 * RelatedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedRepository extends \Doctrine\ORM\EntityRepository
{
}
