<?php

namespace Maci\PageBundle\Repository\Blog;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	public function getList($locale)
	{
		$q = $this->createQueryBuilder('t');
		$q
			->where('t.locale = :locale')
			->setparameter(':locale', $locale)
			->orderBy('t.name', 'ASC')
			;
		return $q->getQuery()->getResult();
	}
}
