
maci_blog_post_permalink:
    path:  /post/{link}
    defaults: { _controller: MaciPageBundle:Blog:postShortlink }

maci_blog_post_shortlink:
    path:  /p/{link}
    defaults: { _controller: MaciPageBundle:Blog:postShortlink }

maci_blog_add_comment:
    path:  /blog/add-comment/{id}
    defaults: { _controller: MaciPageBundle:Blog:addComment }
    requirements:
        id: \d+

maci_blog_author:
    path:  /{_locale}/blog/author/{path}
    defaults: { _controller: MaciPageBundle:Blog:author }
    requirements:
        _locale: "%r_locales%"
        path: .+

maci_blog_tag:
    path:  /{_locale}/blog/{path}
    defaults: { _controller: MaciPageBundle:Blog:tag }
    requirements:
        _locale: "%r_locales%"
        path: .+

maci_blog_show:
    path:  /{_locale}/post/{path}
    defaults: { _controller: MaciPageBundle:Blog:show }
    requirements:
        _locale: "%r_locales%"
        path: .+

maci_blog:
    path:  /{_locale}/blog
    defaults: { _controller: MaciPageBundle:Blog:index }
    requirements:
        _locale: "%r_locales%"
