
maci_mailer_send_mail:
    path:     /mailer/send-mail/{token}
    defaults: { _controller: MaciPageBundle:Mailer:sendMail }

maci_mailer_send_page:
    path:     /mailer/send-page
    defaults: { _controller: MaciPageBundle:Mailer:sendPage, section: mails }

maci_mailer_get_nexts:
    path:     /mailer/get-nexts
    defaults: { _controller: MaciPageBundle:Mailer:getNexts }

maci_mailer_send_next:
    path:     /mailer/send-next
    defaults: { _controller: MaciPageBundle:Mailer:sendNext }

maci_mailer_import:
    path:     /mailer/import
    defaults: { _controller: MaciPageBundle:Mailer:import, section: mails }


maci_mailer_templates_order_confirmed:
    path:     /mailer/templates/order_confirmed
    defaults: { _controller: MaciPageBundle:Mailer:orderConfirmedTemplate }

maci_mailer_templates_order_shipped:
    path:     /mailer/templates/order_shipped
    defaults: { _controller: MaciPageBundle:Mailer:orderShippedTemplate }

maci_mailer_templates_subscription_complete:
    path:     /mailer/templates/subscription_complete
    defaults: { _controller: MaciPageBundle:Mailer:subscriptionCompleteTemplate }

maci_mailer_templates:
    path:     /mailer/templates
    defaults: { _controller: MaciPageBundle:Mailer:templates, section: mails }


maci_mailer:
    path:     /mailer
    defaults: { _controller: MaciPageBundle:Mailer:index }



maci_mailer_user_mails:
    path:     /notifications/
    defaults: { _controller: MaciPageBundle:Mailer:userMails }

maci_mailer_show:
    path:     /mailer/show/{token}
    defaults: { _controller: MaciPageBundle:Mailer:show }
    requirements:
        token: .+



maci_mailer_unsubscribe:
    path:     /newsletter/unsubscribe/{token}
    defaults: { _controller: MaciPageBundle:Mailer:unsubscribe }
    requirements:
        token: .+

maci_mailer_manage_redirect:
    path:     /newsletter/manage/{token}
    defaults: { _controller: MaciPageBundle:Mailer:manageRedirect }
    requirements:
        token: .+

maci_mailer_manage:
    path:     /{_locale}/newsletter/manage/{token}
    defaults: { _controller: MaciPageBundle:Mailer:manage }
    requirements:
        _locale: "%r_locales%"
        token: .+

maci_mailer_subscribe:
    path:     /{_locale}/newsletter/subscribe
    defaults: { _controller: MaciPageBundle:Mailer:subscribe }
    requirements:
        _locale: "%r_locales%"

