
# ---> Set Cookie
maci_set_cookie:
    path:  /set-cookie/{cookie}
    defaults: { _controller: MaciPageBundle:Page:setCookie }

# ---> Page Not Found
maci_page_not_found:
    path:  /{_locale}/page-not-found
    defaults: { _controller: MaciPageBundle:Page:pageNotFound }
    requirements:
        _locale: "%r_locales%"

# ---> Show Page
maci_page:
    path:  /{_locale}/{path}
    defaults: { _controller: MaciPageBundle:Page:page }
    requirements:
        _locale: "%r_locales%"
        path: .+

# ---> Local Homepage
maci_homepage:
    path:  /{_locale}
    defaults: { _controller: MaciPageBundle:Page:localIndex }
    requirements:
        _locale: "%r_locales%"

# ---> Redirect
maci_redirect:
    path:  /{redirect}
    defaults: { _controller: MaciPageBundle:Page:redirect }

# ---> Locale Redirect
homepage:
    path:  /
    defaults: { _controller: MaciPageBundle:Page:index }


