
maci_record_import:
    path:     /record/import
    defaults: { _controller: MaciPageBundle:Record:import, section: records }

maci_record_export:
    path:     /record/export
    defaults: { _controller: MaciPageBundle:Record:export, section: records }

maci_record_load_unsetted_records:
    path:     /record/load-unsetted-records
    defaults: { _controller: MaciPageBundle:Record:loadUnsettedRecords, section: records }

maci_record_export_record:
    path:     /record/export-record
    defaults: { _controller: MaciPageBundle:Record:exportRecord, section: records }

maci_record_labels:
    path:     /record/labels
    defaults: { _controller: MaciPageBundle:Record:labels, section: records }

maci_record_get_labels:
    path:     /record/get-labels
    defaults: { _controller: MaciPageBundle:Record:getLabels, section: records }

maci_record_get_report:
    path:     /record/get-report
    defaults: { _controller: MaciPageBundle:Record:getLabels, section: records, template: report }
