
maci_record_import:
    path:     /record/import
    defaults: { _controller: MaciPageBundle:Record:import, section: records }

maci_record_sales:
    path:     /record/sales
    defaults: { _controller: MaciPageBundle:Record:sales, section: records }

maci_record_load_unsetted_records:
    path:     /record/load-unsetted-records
    defaults: { _controller: MaciPageBundle:Record:loadUnsettedRecords }

maci_record_labels:
    path:     /record/labels
    defaults: { _controller: MaciPageBundle:Record:labels, section: records }

maci_record_get_labels:
    path:     /record/get-labels
    defaults: { _controller: MaciPageBundle:Record:getLabels }
