
maci_product_show:
    path:  /{_locale}/product/{path}
    defaults: { _controller: MaciPageBundle:Shop:show }
    requirements:
        _locale: "%r_locales%"

maci_product_category:
    path:  /{_locale}/shop/{path}
    defaults: { _controller: MaciPageBundle:Shop:category }
    requirements:
        _locale: "%r_locales%"

maci_product:
    path:  /{_locale}/shop
    defaults: { _controller: MaciPageBundle:Shop:index }
    requirements:
        _locale: "%r_locales%"

maci_shop_import:
    path:     /shop/import
    defaults: { _controller: MaciPageBundle:Shop:import, section: shop }

maci_shop_sales:
    path:     /shop/sales
    defaults: { _controller: MaciPageBundle:Shop:sales, section: shop }

maci_shop_load_unsetted_records:
    path:     /shop/load-unsetted-records
    defaults: { _controller: MaciPageBundle:Shop:loadUnsettedRecords }
