
maci_product_add_variant:
    path:  /{_locale}/product/add-variant/{id}
    defaults: { _controller: MaciPageBundle:Shop:addVariant }
    methods:  [POST]
    requirements:
        id: \d+
        _locale: "%r_locales%"

maci_product_set_variant_type:
    path:  /{_locale}/product/set-variant-type/{id}
    defaults: { _controller: MaciPageBundle:Shop:setVariantType }
    methods:  [POST]
    requirements:
        id: \d+
        _locale: "%r_locales%"

maci_product_show:
    path:  /{_locale}/product/{path}
    defaults: { _controller: MaciPageBundle:Shop:show }
    requirements:
        _locale: "%r_locales%"

maci_product_category:
    path:  /{_locale}/shop/{path}
    defaults: { _controller: MaciPageBundle:Shop:category }
    requirements:
        _locale: "%r_locales%"

maci_product:
    path:  /{_locale}/shop
    defaults: { _controller: MaciPageBundle:Shop:index }
    requirements:
        _locale: "%r_locales%"
